spring.application.name=gateway-service
server.port=5555

# Datasource
#spring.datasource.url=jdbc:mysql://localhost:3306/gwdb?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#
#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-circular-references=true
spring.datasource.url=jdbc:postgresql://localhost:5432/gatewaydb
spring.datasource.username=postgres
spring.datasource.password=root

#FOR AWS EC2 INSTANCE
#spring.datasource.url=${jdbcurl}
#spring.datasource.username= ${dbuser}
#spring.datasource.password=${dbpwd}

#spring.datasource.driver-class-name=org.postgresql.Driver

#TO AVOID RUNNING OF "Data.sql" file
#spring.datasource.initialization-mode=never


#none => Here we dont want tables to be created by our java code
#validate => Allows to checks compliance between java class's attibutes and their equivalent table's columns in db
#spring.jpa.hibernate.ddl-auto=create

# Fix Postgres JPA Error (Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented).
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.show-sql=true
spring.main.web-application-type=reactive
spring.main.allow-bean-definition-overriding=true
eureka.client.enabled=false

#service.security.secure-key-username=randomSecureKeyUsername!
#service.security.secure-key-password=randomSecureKeyPassword!

# Key depends on JWT algorithm;
# if RSA => needs public, private;
# if HMAC => needs only single key....
app.jwt.secret=randomSecretKey10987654321!

# one day in ms
app.jwt.expiration-in-ms=86400000